[package]
name = "stproto"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["31core"]

[dependencies]
rust-crypto = "0.2.36"
rand = "0.8.5"
rsa = "0.8.1"
zstd = "0.12.4"
flate2 = "1.0.26"
lzma-rs = "0.3.0"
chacha20 = "0.9.1"

[lib]
crate-type = ["cdylib", "rlib"]
